### PR TITLE
Updating the main hero image for the home page

### PR DESCRIPTION
**Pull request by mgifford**
This is about machine readable code.

### CODE REVIEW

**Review by dmundra — CHANGES_REQUESTED** [review]
@mgifford we don't use the the uswds files from `openacr/uswds` in the actual Jekyll site, those styles are only applied to the openacr html pages. To add customizes to the Jekyll site including different hero images you have to adjust the files in `https://github.com/GSA/openacr-website/tree/main/_assets`. Apologizes for the confusing folders.

**Comment by mgifford** [comment]
No problem @dmundra totally makes sense not to put it in the USWDS directory.  

Now how do I refer to the asset directory `$theme-hero-image: "#{$theme-image-path}/mra11y-hero.png" !default;` isn't going to work. 

Not sure how to bring forward what I'm trying in the footer:
`{% asset gsa-footer-logo.png width="50" alt="GSA logo" %}`

Been a while since I worked with this.

**Comment by dmundra** [comment]
@mgifford may I try something? Also it looks federalist is not running for you. I am troubleshooting that as well.

**Comment by dmundra** [comment]
@mgifford submitted a PR https://github.com/GSA/openacr-website/pull/32 to update this branch.

**Review by dmundra — APPROVED** [review]
Works locally. Have to fix federalist next but will merge this.

**Pull request merged**
