### PR TITLE
adding accordion and fixing mobile view of menu

### PR DESCRIPTION
**Pull request by danid123**

### CODE REVIEW

**Comment by dmundra** [comment]
@danid123 the drop-down menu works well but I don't see the sidebar in the mobile page. I think it handy to see the sidebar even though the user can get to it in the menu dropdown. Maybe removing `display-none` class would be sufficient? Happy to discuss more.

URL I used: https://federalist-6d3494a6-5b03-42fa-82f2-57f3bbb203af.app.cloud.gov/preview/gsa/openacr-website/add-sidenav-on-mobile/about/

**Review by dmundra — CHANGES_REQUESTED** [review]
Minor change to get the sidebar to appear.

**Comment by danid123** [comment]
For how much text there is and how small the screen is I think the sidebar on mobile would hinder reading. Other USWDS sites follow the same pattern:
https://www.plainlanguage.gov/about/
https://www.ncbi.nlm.nih.gov/sars-cov-2/

This one doesn't and I think it looks a little odd on mobile:
https://www1.grc.nasa.gov/space/

Clicking around on the sites in the [USWDS showcase](https://designsystem.digital.gov/getting-started/showcase/all/) it seems to be split 40/60 in favor of hiding the sidebar on mobile. I think most of the ones that hide it are copy-heavy like ours. I could go either way but think hiding it means less scrolling for the user.

**Comment by dmundra** [comment]
@danid123 thanks for the examples. That makes sense.

**Review by dmundra — APPROVED** [review]
I am convinced. Approved

**Pull request merged**
